### ISSUE TITLE
graphics corruptions

### ISSUE THREAD

**Issue by username7291** [LibVNC/x11vnc#119] opened 2019-12-26 19:06 UTC
Since Raspbian Buster x11vnc make errors in graphics. It doesnt happend on the old OS Versions.
The Deverloper of Raspbian dont care much about compatiblity, so i ask here.
There is not much to describe no special steps to reproduce, see attched image(if this work). I tryed x11vnc 0.9.13 and compiled the one here&libvncserver from git. The result is the same.

 - OS and version: Rasbian Buster Release date: 2019-09-26
 - Xorg version used: ?
 - Wayland version used: ?
 
There is another Bug https://github.com/LibVNC/x11vnc/issues/88 the horizotal movement looks pretty same. The guy use another OS but too a raspberry.

**Comment by username7291** [comment] 2019-12-26 19:09
Uploading of images is broken on GIT.
<a href="https://ibb.co/RDrfSw0"><img src="https://i.ibb.co/HHw628z/PI4-GFXBug-VNC.jpg" alt="PI4-GFXBug-VNC" border="0"></a>

**Comment by bk138** [comment] 2019-12-27 16:12
Let's handle this as a dupe of #88 and gather info there, @username7291 !

**Closed by bk138** 2019-12-27 16:12 UTC
Labels: bug
