### ISSUE TITLE
Ubuntu 18.04 ARM64 w/ XFCE 4.12 - stack smash randomly

### ISSUE THREAD

**Issue by FalcoGer** [LibVNC/x11vnc#79] opened 2018-08-21 06:35 UTC
I'm using Ubuntu 18.04 arm64 on a Raspberry Pi 3B. I use xrdp with x11vnc to connect through windows rdp. It works well to look at the display, however when hitting keys and taking actions that change large portions of the screen, then the x11vnc server closes, saying it received signal 6 and had a stack smash.

x11vnc version: 0.9.13 lastmod: 2011-08-10 (ubuntu bionic repository version)
xfce version 4.12
xorg version x11r7 (I think. Xorg -version throws me 'only console users may run this')

I'm running a display (and only that display) on a ribbon cable that's connected to the pi's display output. This may or may not be related, probably isn't though.

So what I did to create this logfile is to run
`x11vnc -nopw -o ~/Desktop/x11vnc_crash.log -debug_pointer -debug_keyboard -debug_tiles -debug_sel -debug_grabs -debug_scroll -debug_wireframe -debug_ncache`
for testing. normally I'd run:
`env UNIXPW_DISABLE_SSL=1 x11vnc -display :0 -auth .Xauthority -rfbport 5900 -no6 -shared –forever –loop2000 -localhost -unixpw -solid #000044 -oa /var/log/vncserver.log -wait 50 -xdamage -ncache 10 -ncache_cr`
from xfce autostart (~/.config/autostart)

Then I opened a terminal and hit new tab a couple of times (ctrl + shift + t), which caused a crash. I did not record that one. So I reopened and attempted to close the tabs in the terminal window. This is the crash recorded:

[x11vnc_crash.log](https://github.com/LibVNC/x11vnc/files/2305093/x11vnc_crash.log)

I don't need it often, but It must run stable.
I tried running with -noxdamge -nowf -noncache:
`x11vnc -display :0 -auth .Xauthority -rfbport 5900 -no6 -shared -forever -localhost -o ~/Desktop/x11vnc_crash2.log -wait 50 -noxdamage -noncache -nowf -debug_pointer -debug_keyboard -debug_tiles -debug_sel -debug_grabs -debug_scroll -debug_wireframe -debug_ncache`
It still crashes like so (closing tabs in xfce term again):

[x11vnc_crash2.log](https://github.com/LibVNC/x11vnc/files/2305140/x11vnc_crash2.log)

**Comment by bk138** [comment] 2018-08-21 08:17
You should update to a newer version. Dupe of #27 and #61.

**Closed by bk138** 2018-08-21 08:17 UTC

**Comment by timmc** [comment] 2018-09-15 20:01
If you didn't catch it from the comments in those duplicate tickets, you can try adding `-noxrecord`. That worked for me on Debian 9 as well.
